### ISSUE TITLE
Does not compile on GHC 7.10.2, out of date dependencies

### ISSUE THREAD

**Issue by simonvandel** [jfischoff/gdiff-th#2]
Template haskell is 2.10.0 in GHC 7.10.2
gdiff 1.1 is available on Hackage

**Comment by jfischoff** [comment]
I don't have the time to fix this. Feel free to send in a pull request

**Comment by ggreif** [comment]
@simonvandel you can consider writing pattern synonyms as an abstraction layer for 7.10 (or vice versa). Also, there are libraries out there (see goldfirere's) which can possibly help.

**Comment by simonvandel** [comment]
I will look into this, but I have no experience with template haskell, or advanced haskell, so I can not guarantee a solution.
